# -*- coding: utf-8 -*-
"""bugün.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RSCd6ozO8pn8lanZupz3ZWCeDZtUTFkl
"""

import os
books = open("books.txt", "w")
open("books.txt", "w")
books.write("Gece Yarısı Kütüphanesi, Matt Haig - Körlük, José Saramago -  Dönüşüm, George Orwell -  Otomatik Portakal, Anthony Burgess - Simyacı, Paulo Coelho")
books.close()

class books:
  def __init__(self, adi, yazar, sayfa, basim):
      self.adi =  adi
      self.yazar = yazar
      self.sayfa= sayfa
      self.basim = basim

  def bilgileri_goster(self):
      print("Kitabın adı:" , self.adi)
      print("Kitabın yazarı:" , self.yazar)
      print("Kitabın sayfa sayısı:", self.sayfa)
      print("Kitabın basım tarihi:", self.basim)

book1 = books("Gece Yarısı Kütüphanesi", "Matt Haig", "296", "2021")
book2 = books("Körlük", "José Saramago", "1995", "320" )
book3 = books("Hayvan Çiftliği", "George Orwell", "1945", "152")
book4 = books("Otomatik Portakal", "Anthony Burgess", "1961", "176")
book5 = books("Simyacı", "Paulo Coelho", "1988", "188")

ans=True
while ans:
    print ("""
    **MENÜ**
    1.Kitapları Listele
    2.Kitap Ekle
    3.Kitap çıkar
    q.Çıkış
          """)
    ans=input("Seçiminizi girin (1-4)")
    if ans=="1":
      open("books.txt", "r")
      print("Kitaplar listelendi.")
    elif ans=="2":
      adi = input("Kitap adı:" '\n')
      yazar = input("Kitabın yazarı:" '\n')
      sayfa = input("Kitabın sayfa sayısı:" '\n')
      basim = input("Kitabın basım tarihi:" '\n')
      open("books.txt", "w")
      print("\n Kitap Eklendi")
    elif ans=="3":
      adi = input("Kitabın ismi?")
      if os.path.exists("books.txt"):
          os.remove("books.txt")
      print("\n Kitap Kaldırıldı")
    elif ans=="q":
      print("\n Çıkış")
    elif ans !="":
      print("\n Geçersiz Deneme")